### ISSUE TITLE
@TestCase error with Nette Tester 2.4.0

### ISSUE THREAD

**Issue by petrparolek** [mangoweb-backend/tester-infrastructure#8]
Version: v0.4

### Bug Description
Test with annotation @tesrCase fails: ` Cannot list TestCase methods in file '/home/vagrant/projects/pp-is/tests/PresenterTests/SomePresenterTest.phpt'. Do you call TestCase::run() in it?` 

Commit https://github.com/nette/tester/commit/cf1d7eb58ca72cafaf8795f8a7f5b71becb18128 in PR https://github.com/nette/tester/pull/378 breaks tests.

### Steps To Reproduce
````
<?php declare(strict_types = 1);

namespace AppTests\Presenters;

use Mangoweb\Tester\Infrastructure\TestCase;
use Mangoweb\Tester\PresenterTester\PresenterTester;

$testContainerFactory = require __DIR__ . '/../bootstrap.php';

/** @testCase */
class SomePresenterTest extends TestCase
{

	/** @var PresenterTester */
	private $presenterTester;

	public function __construct(PresenterTester $presenterTester)
	{
		$this->presenterTester = $presenterTester;
	}


}

SomePresenterTest::run($testContainerFactory);
````

**Comment by matej21** [comment]
fixed in 593b8420c643598a7833613e696b1813d097dcee
