### ISSUE TITLE
nette/tester dependency in v0.5

### ISSUE THREAD

**Issue by martenb** [mangoweb-backend/tester-infrastructure#9]
Dependency was changed, from `~2.0` to `~2.3.1`, that causes downgrading of nette/tester in our projects..

![image](https://user-images.githubusercontent.com/13311472/111279027-8b67e880-863a-11eb-86a2-bf324f3ac132.png)

I thing, that it should be ^2.3.1 instead...

**Comment by matej21** [comment]
thanks, fixed 32b83da2c61b3b3e03cf70b74900a0b209a7d2ac
